### ISSUE TITLE
Does not work with music videos.

### ISSUE THREAD

**Issue by zalazarc20** [dangdungcntt/youtube-stream-url#14]
First of all, your project is amazing and sorry for my english

ok the problem is that when searching for songs it does not bring the formats, I leave an example capture
![example](https://i.imgur.com/J7wa5TQ.png)

**Comment by dangdungcntt** [comment]
Hi, this kind of video need decode signature cipher. I will implement it ASAP. Thanks

**Comment by dangdungcntt** [comment]
Fixed. Please update to latest version (2.2.1).Note: Youtube validate IP when play copyright music video
