### ISSUE TITLE
The package no longer works.

### ISSUE THREAD

**Issue by lzx19951022** [dangdungcntt/youtube-stream-url#15]
Hi, I tried the package recently and found that it no longer works, when I run the code, it returns "false", following is the screenshoot.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/35286852/197373120-870bc65c-528d-4945-aab9-9cfe54f03f6e.png">

**Comment by dangdungcntt** [comment]
It still works on my device. May be you hit YouTube region restriction. Can you try with other video you can watch on browser?

**Comment by lzx19951022** [comment]
Hi, I tried another YouTube live stream, and still got the same result. I can watch the live stream on the browser, but it doesn't work on the package.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/35286852/197432781-9447be1b-305d-436e-98a4-aaf6d6555ef5.png">


<img width="1198" alt="image" src="https://user-images.githubusercontent.com/35286852/197432708-e20fb228-6207-497e-ac8e-17a2f2c3ed13.png">

**Comment by dangdungcntt** [comment]
Are you using VPN on browser? For now, I can't reproduce your case, so I will update package to throw error when cannot get video info.

**Comment by lzx19951022** [comment]
Yes, I am in China mainland so I have to use vpn. But the package worked fine during the past several months without any problem, then suddenly it didn't work. Thank you for the helping. I appreciate it.

**Comment by lzx19951022** [comment]
And the vpn is applied on the router. I can directly browse any blocked website on my device without using VPN on it.

**Comment by dangdungcntt** [comment]
In new version (2.4.0), you can pass option `throwOnError: true` to debug response error. [View example here](https://github.com/dangdungcntt/youtube-stream-url#handle-error)

**Comment by dangdungcntt** [comment]
`response.data` should be a valid HTML content of url `https://www.youtube.com/watch?v=<video-id>`, otherwise package can't get video link
