### ISSUE TITLE
False negative on stream because of 'response.data.indexOf("errorcode") > -1'

### ISSUE THREAD

**Issue by yomomano** [dangdungcntt/youtube-stream-url#16]
Hi, I found that YT video ID 'xFrGuyw1V8s' randomly fails so I debugged a bit and find that the condition 'response.data.indexOf("errorcode") > -1' causes false negatives for this stream: when removing this condition in getInfo(), the stream loads normally always...

As mentioned, the failure seems to happen randomly. No idea why 'errorcode' sometimes occurs and sometimes doesnt. Maybe it's because of ABBA? :)

Please try with YT video ID 'xFrGuyw1V8s'

Thanks

**Comment by dangdungcntt** [comment]
Can you send PR for this fix?

**Comment by yomomano** [comment]
Done. Thanks !
