### ISSUE TITLE
403 Error on nodeJS

### ISSUE THREAD

**Issue by barzaken** [dangdungcntt/youtube-stream-url#19]
Hello . 
on node server that running on render.com , i always get 403 no permission error with borken url link to the video, on local everything works fine. 
EDIT : On local it works on anything(videoId/songId) , on node only on videoId, any ideas why it cant fetch a url with songId? any help is appreciated !

**Comment by dangdungcntt** [comment]
Are you try to get link of Music Video? Youtube validate IP when play copyright music video. 
So you must use same IP when get and play video.
I think you can use your node server as a proxy service, that sit between your browser and YouTube server.

**Comment by barzaken** [comment]
> Are you try to get link of Music Video? Youtube validate IP when play copyright music video. So you must use same IP when get and play video. I think you can use your node server as a proxy service, that sit between your browser and YouTube server.

Do you have any idea/example how to implement your libary with proxy server?

**Comment by dangdungcntt** [comment]
You can implement like this answer from [SO](https://stackoverflow.com/a/71537731).

**Comment by barzaken** [comment]
`async function getSongById(req, res) {
    console.log(req.params.id);
    try {
        console.log('Getting song');
        if (!req) return
        let song = await Youtube.getInfo({ url: `https://www.youtube.com/watch?v=${req.params.id}`, throwOnError: true })
        const regex = new RegExp('AUDIO_QUALITY_MEDIUM', 'i');
        song.formats = song.formats.filter(format => regex.test(format.audioQuality))
        axios.get(song.formats.pop().url, { responseType: 'stream' })
            .then((axiosResp) => {
                res.set({
                    'Content-Type': axiosResp.headers['content-type']
                })
                axiosResp.data.pipe(res)
            })
        // res.json(song.formats.pop().url)
    } catch (err) {
        console.log('ERROR FROM YOUTUBE!!!!', err);
    }
}`

**Comment by barzaken** [comment]
or maybe i need to modify the actual package? maybe add in this req the clientIp or something ? 
```
const $4fa36e821943b400$var$getInfo = async ({ url: url , throwOnError: throwOnError = false  })=>{
    let videoId = $4fa36e821943b400$var$getVideoId({
        url: url
    });
```
