### ISSUE TITLE
Download speed too slow

### ISSUE THREAD

**Issue by trantrung22** [dangdungcntt/youtube-stream-url#20]
The download speed is limited at ~40-70KB/s only. Whereas other tool can be > 10MB/s

**Comment by dangdungcntt** [comment]
My package just return googlevideo link, so download speed depends on your connection to Google Server. Currently, Vietnam's internet speed affected by broken undersea cable route.

**Comment by dangdungcntt** [comment]
My package just return googlevideo link, so download speed depends on your connection to Google Server. Currently, Vietnam's internet speed affected by broken undersea cable route.

**Comment by trantrung22** [comment]
> My package just return googlevideo link, so download speed depends on your connection to Google Server. Currently, Vietnam's internet speed affected by broken undersea cable route.

I'm afraid your links still not correctly decoded, so it get throttled by Youtube. Please try yt-dlp for your reference. It's link can be downloaded very fast.
