### ISSUE TITLE
some youtube URLs don't return any formats

### ISSUE THREAD

**Issue by davidsalib** [dangdungcntt/youtube-stream-url#9]
For some youtube videos, the package finds zero formats. 
It finds the video details, but formats is an array with 0 elements. 

I tried with a python package to test (https://pypi.org/project/pytube/), and it **does** find stream URLs. 

Anybody have an idea why some videos aren't returning formats?
(here's the video I tried: https://www.youtube.com/watch?v=5k5gVe4H-A0)

![image](https://user-images.githubusercontent.com/10209934/107137734-acffe280-68cc-11eb-81c3-32d9024696ec.png)

**Comment by MVDW-Java** [comment]
I have the same problem, It happens with some videos while others are working.
Don't know why it won't return any formats.
Its just strange

**Comment by MVDW-Java** [comment]
Update: After experimenting a bit I realized it does not put anything in formats when it contains copyrighted music.

**Comment by dangdungcntt** [comment]
I switched to [node-ytdl-core](https://github.com/fent/node-ytdl-core).
